name: sample-workflow
on:
  push:
    branches: [master]
    
jobs:
  jobs:
  runs-on: ubuntu-latest
  steps:
  - name: checks-out your repository under $GITHUB_WORKSPACE
    uses: actions/checkoout@v2
  - name: use echo command
    run: echo "sample-workflow"
